//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Sessions Sessions { get; set; }
        public virtual Users Users { get; set; }
    }
}
